export const STORAGE_KEYS = {
  RULES: 'rules',
  SCHEDULES: 'schedules',
  FOCUS_END: 'focus_mode_end_time',
  LAST_RESET: 'last_reset_day',
  PROFILE_ID: 'nextdns_profile_id',
  API_KEY: 'nextdns_api_key',
  LOGS: 'app_system_logs',
  USAGE_HISTORY: 'usage_history',
  SESSION: 'fg_active_session',
  SESSION_HISTORY: 'fg_session_history',
  SESSION_START: 'fg_focus_session_start',
  BLOCKED_DOMAINS: 'blocked_domains',
  BLOCK_DEBUG: 'fg_block_debug',
  RUNTIME_ERROR: 'fg_last_runtime_error',
  USAGE: 'usage',
  TEMP_PASSES: 'fg_temp_passes',
  EXTENSION_COUNTS: 'fg_extension_counts',
  SYNC_MODE: 'fg_sync_mode',
  CONNECTION_STATUS: 'nextdns_connection_status',
  CACHED_METADATA: 'cached_ndns_metadata',
  SYNC_STATE: 'sync_state',
  STRICT_MODE: 'strict_mode_enabled',
  THEME: 'fg_appearance_theme',
  ICON_CACHE: 'fg_icon_cache',
  ONBOARDING_DONE: 'fg_onboarding_done',
};
