import { BrandDefinition } from '@focusgate/types';

export const BRAND_DATA: Record<string, BrandDefinition> = {
  '9gag': {
    slug: '9gag',
    color: '#ffffff',
    domain: '9gag.com',
  },
  amazon: {
    source: 'favicon',
    color: '#FF9900',
    domain: 'amazon.com',
  },
  bereal: {
    slug: 'bereal',
    color: '#ffffff',
    domain: 'bere.al',
  },
  blizzard: {
    source: 'favicon',
    color: '#00B4FF',
    domain: 'blizzard.com',
  },
  bumble: {
    source: 'favicon',
    color: '#FFCB37',
    domain: 'bumble.com',
  },
  chatgpt: {
    source: 'favicon',
    color: '#10a37f',
    domain: 'chatgpt.com',
  },
  dailymotion: {
    slug: 'dailymotion',
    color: '#0066DC',
    domain: 'dailymotion.com',
  },
  discord: { slug: 'discord', color: '#5865F2', domain: 'discord.com' },
  disneyplus: {
    source: 'favicon',
    color: '#113CCF',
    domain: 'disneyplus.com',
  },
  ebay: { slug: 'ebay', color: '#E53238', domain: 'ebay.com' },
  facebook: { slug: 'facebook', color: '#1877F2', domain: 'facebook.com' },
  fortnite: {
    source: 'favicon',
    color: '#ffffff',
    domain: 'fortnite.com',
  },
  google: { slug: 'google', color: '#4285F4', domain: 'google.com' },
  googlechat: {
    source: 'favicon',
    color: '#34A853',
    domain: 'chat.google.com',
  },
  hbomax: {
    source: 'favicon',
    color: '#8B5CF6',
    domain: 'max.com',
  },
  hulu: {
    source: 'favicon',
    color: '#1CE783',
    domain: 'hulu.com',
  },
  imgur: { slug: 'imgur', color: '#1BB76E', domain: 'imgur.com' },
  instagram: {
    slug: 'instagram',
    color: '#E4405F',
    domain: 'instagram.com',
  },
  leagueoflegends: {
    source: 'favicon',
    color: '#C89B3C',
    domain: 'leagueoflegends.com',
  },
  linkedin: { slug: 'linkedin', color: '#0077B5', domain: 'linkedin.com' },
  mastodon: {
    slug: 'mastodon',
    color: '#6364FF',
    domain: 'mastodon.social',
  },
  messenger: {
    source: 'favicon',
    color: '#0084FF',
    domain: 'messenger.com',
  },
  minecraft: {
    source: 'favicon',
    color: '#62B74A',
    domain: 'minecraft.net',
  },
  netflix: { slug: 'netflix', color: '#E50914', domain: 'netflix.com' },
  openai: { slug: 'openai', color: '#10a37f', domain: 'openai.com' },
  pinterest: {
    slug: 'pinterest',
    color: '#BD081C',
    domain: 'pinterest.com',
  },
  playstation: {
    slug: 'playstation',
    color: '#003791',
    domain: 'playstation.com',
  },
  'playstation-network': {
    slug: 'playstation',
    color: '#003791',
    domain: 'playstation.com',
  },
  primevideo: {
    source: 'favicon',
    color: '#00A8E1',
    domain: 'primevideo.com',
  },
  reddit: { slug: 'reddit', color: '#FF4500', domain: 'reddit.com' },
  roblox: { slug: 'roblox', color: '#000000', domain: 'roblox.com' },
  signal: { slug: 'signal', color: '#3A76F0', domain: 'signal.org' },
  skype: {
    source: 'favicon',
    color: '#00AFF0',
    domain: 'skype.com',
  },
  slack: { slug: 'slack', color: '#4A154B', domain: 'slack.com' },
  snapchat: {
    source: 'favicon',
    color: '#FFFC00',
    domain: 'snapchat.com',
  },
  spotify: { slug: 'spotify', color: '#1DB954', domain: 'spotify.com' },
  steam: { slug: 'steam', color: '#ffffff', domain: 'steampowered.com' },
  telegram: { slug: 'telegram', color: '#26A5E4', domain: 'telegram.org' },
  teams: {
    slug: 'microsoftteams',
    color: '#6264A7',
    domain: 'teams.microsoft.com',
  },
  tiktok: { slug: 'tiktok', color: '#ffffff', domain: 'tiktok.com' },
  tinder: {
    source: 'favicon',
    color: '#FF4458',
    domain: 'tinder.com',
  },
  tumblr: { slug: 'tumblr', color: '#36465D', domain: 'tumblr.com' },
  twitch: { slug: 'twitch', color: '#9146FF', domain: 'twitch.tv' },
  twitter: { slug: 'x', color: '#ffffff', domain: 'x.com' },
  vimeo: { slug: 'vimeo', color: '#1AB7EA', domain: 'vimeo.com' },
  vk: {
    source: 'favicon',
    color: '#0077FF',
    domain: 'vk.com',
  },
  whatsapp: { slug: 'whatsapp', color: '#25D366', domain: 'whatsapp.com' },
  x: { slug: 'x', color: '#ffffff', domain: 'x.com' },
  xbox: { slug: 'xbox', color: '#107C10', domain: 'xbox.com' },
  xboxlive: { slug: 'xbox', color: '#107C10', domain: 'xbox.com' },
  youtube: { slug: 'youtube', color: '#FF0000', domain: 'youtube.com' },
  viber: {
    source: 'favicon',
    color: '#7360F2',
    domain: 'viber.com',
  },
  yahoo: {
    source: 'favicon',
    color: '#6001D2',
    domain: 'yahoo.com',
  },
  zoom: { slug: 'zoom', color: '#2D8CFF', domain: 'zoom.us' },
};
