import { COLORS } from './designTokens';
import { ICONS } from '@/ui/Icons';

const TOKEN_DEFS = {
  HEADING: {
    fontSize: '1rem',
    fontWeight: '600',
    color: 'var(--fg-text)',
    letterSpacing: '0',
    lineHeight: '1.4',
  },
  HERO: {
    fontSize: '1.25rem',
    fontWeight: '700',
    color: 'var(--fg-text)',
    letterSpacing: '0',
    lineHeight: '1.3',
  },
  LABEL: {
    fontSize: '14px',
    fontWeight: '600',
    color: 'var(--fg-text)',
    letterSpacing: '0',
    lineHeight: '1.4',
  },
  SUBTEXT: {
    fontSize: '13px',
    fontWeight: '500',
    color: 'var(--fg-muted)',
    lineHeight: '1.5',
  },
  CARD_TITLE: {
    fontSize: '13px',
    fontWeight: '600',
    letterSpacing: '0',
    color: 'var(--fg-text)',
    lineHeight: '1.4',
  },
  BADGE: {
    fontSize: '12px',
    fontWeight: '700',
    letterSpacing: '0',
  },
  STAT: {
    fontSize: '24px',
    fontWeight: '700',
    letterSpacing: '0',
    color: 'var(--fg-text)',
    lineHeight: '1.1',
  },
  STAT_LARGE: {
    fontSize: '48px',
    fontWeight: '800',
    letterSpacing: '0',
    color: 'var(--fg-text)',
    lineHeight: '1',
  },
  WIDGET_LABEL: {
    fontSize: '14px',
    fontWeight: '600',
    color: 'var(--fg-muted)',
    letterSpacing: '0',
    lineHeight: '1.4',
  },
  BANNER_HEADING: {
    fontSize: '1.05rem',
    fontWeight: '700',
    color: 'var(--fg-text)',
    letterSpacing: '0',
    lineHeight: '1.4',
  },
  BANNER_BODY: {
    fontSize: '13px',
    fontWeight: '400',
    color: 'var(--fg-text)',
    opacity: '0.9',
    lineHeight: '1.6',
  },
  ERROR: {
    fontSize: '14px',
    fontWeight: '600',
    color: 'var(--fg-red)',
    letterSpacing: '0',
    lineHeight: '1.4',
  },
  FOOTNOTE: {
    fontSize: '12px',
    fontWeight: '400',
    color: 'var(--fg-muted)',
    lineHeight: '1.6',
  },
  SIGN_TITLE: {
    fontSize: '16px',
    fontWeight: '600',
    color: 'inherit',
    letterSpacing: '0.02em',
    lineHeight: '1.3',
    textTransform: 'none',
  },
  SIGN_VALUE: {
    fontSize: '14px',
    fontWeight: '500',
    color: 'inherit',
    letterSpacing: '0.01em',
    lineHeight: '1.3',
    opacity: '0.98',
  },
  MODAL_TITLE: {
    fontSize: '18px',
    fontWeight: '700',
    color: 'var(--fg-text)',
    lineHeight: '1.4',
  },
  MODAL_BODY: {
    fontSize: '13px',
    fontWeight: '400',
    color: 'var(--fg-muted)',
    lineHeight: '1.6',
  },
  BUTTON_TEXT: {
    fontSize: '14px',
    fontWeight: '600',
    letterSpacing: '0',
    color: 'var(--fg-text)',
  },
};

export const UI_ICONS = {
  FIRE: ICONS.FIRE,
  CHECK: ICONS.CHECK,
  ARROW_RIGHT: ICONS.ARROW_RIGHT,
  TRENDS: ICONS.TRENDS,
  SHIELD: ICONS.SHIELD,
  ZAP: ICONS.ZAP,
  LOCK: ICONS.LOCK,
  RULER: ICONS.RULER,
  ROCKET: ICONS.ROCKET,
  TARGET: ICONS.TARGET,
  SPARKLES: ICONS.SPARKLES,
  TURTLE: ICONS.TURTLE,
  CHART: ICONS.CHART,
  LIGHTBULB: ICONS.LIGHTBULB,
  KEYBOARD: ICONS.KEYBOARD,
  CLOSE: ICONS.CLOSE,
  CLOUDSYNC: ICONS.CLOUDSYNC,
  SETTINGS: ICONS.SETTINGS,
  SEARCH: ICONS.SEARCH,
  CLOCK: ICONS.CLOCK,
  EDIT: ICONS.EDIT,
  PLUS: ICONS.PLUS,
  PLAY: ICONS.PLAY,
  PAUSE: ICONS.PAUSE,
  STOP: ICONS.STOP,
  BACK: ICONS.BACK,
  ALERT: ICONS.ALERT,
  ACTIVITY: ICONS.ACTIVITY,
  USER: ICONS.USER,
  SPINNER: ICONS.SPINNER,
  EXTERNAL_LINK: ICONS.EXTERNAL_LINK,
  PIE_CHART: ICONS.PIE_CHART,
  INFO: ICONS.INFO,
  TRIANGLE_ALERT: ICONS.TRIANGLE_ALERT,
  LAYOUT_GRID: ICONS.LAYOUT_GRID,
  PAUSE_CIRCLE: ICONS.PAUSE_CIRCLE,
  CALENDAR: ICONS.CALENDAR,
  SLASH: ICONS.SLASH,
  WIFI_OFF: ICONS.WIFI_OFF,
  LIST: ICONS.LIST,
  DATABASE: ICONS.DATABASE,
  REFRESH: ICONS.REFRESH,
  WIFI: ICONS.WIFI,
  EYE: ICONS.EYE,
  EYE_OFF: ICONS.EYE_OFF,
  LINK: ICONS.LINK,
  HELP_CIRCLE: ICONS.HELP_CIRCLE,
  GOOGLE: ICONS.GOOGLE,
  MAIL: ICONS.MAIL,
  CHROME: ICONS.CHROME,
  FIREFOX: ICONS.FIREFOX,
  HOME: ICONS.HOME,
  SHORTS: ICONS.SHORTS,
  MESSAGE_SQUARE: ICONS.MESSAGE_SQUARE,
  BELL: ICONS.BELL,
  COMPASS: ICONS.COMPASS,
  PALETTE: ICONS.PALETTE,
  RADIO: ICONS.RADIO,
  CLAPPERBOARD: ICONS.CLAPPERBOARD,
  STORY: ICONS.STORY,
  SHOPPING_CART: ICONS.SHOPPING_CART,
  USERS: ICONS.USERS,
  CHEVRON_RIGHT: ICONS.CHEVRON_RIGHT,
  CPU: ICONS.CPU,
  GLOBE: ICONS.GLOBE,
  SLIDERS: ICONS.SLIDERS,
  TYPE: ICONS.TYPE,
  YOUTUBE: ICONS.YOUTUBE,
  CHEVRON_LEFT: ICONS.CHEVRON_LEFT,
  CHEVRON_DOWN: ICONS.CHEVRON_DOWN,
  TRASH: ICONS.TRASH,
  CLOUD: ICONS.CLOUD,
  SUN: ICONS.SUN,
  MONITOR: ICONS.MONITOR,
  MOON: ICONS.MOON,
  SIGN_OUT: ICONS.SIGN_OUT,
  WRENCH: ICONS.WRENCH,
  TRENDING_UP: ICONS.TRENDING_UP,
  ROBOT_LOCK: ICONS.ROBOT_LOCK,
  LAYERS: ICONS.LAYERS,
  GITHUB: ICONS.GITHUB,
  EDGE: ICONS.EDGE,
  GAMES: ICONS.GAMES,
  GAMBLING: ICONS.GAMBLING,
  PORN: ICONS.PORN,
  SOCIAL: ICONS.SOCIAL,
  VIDEO: ICONS.VIDEO,
  SHOPPING: ICONS.SHOPPING,
  DATING: ICONS.DATING,
  PIRACY: ICONS.PIRACY,
  BYTE: ICONS.BYTE,

  // In-app Aliases
  LIVE: ICONS.RADIO,
  REELS: ICONS.CLAPPERBOARD,
  STORIES: ICONS.STORY,
  CART: ICONS.SHOPPING_CART,
  COMMENTS: ICONS.MESSAGE_SQUARE,
};

function toCSS(obj: any): string {
  return Object.entries(obj)
    .map(
      ([k, v]) => `${k.replace(/[A-Z]/g, (m) => '-' + m.toLowerCase())}: ${v};`,
    )
    .join(' ');
}

export const UI_TOKENS = {
  TEXT: {
    HEADING: toCSS(TOKEN_DEFS.HEADING),
    HERO: toCSS(TOKEN_DEFS.HERO),
    LABEL: toCSS(TOKEN_DEFS.LABEL),
    SUBTEXT: toCSS(TOKEN_DEFS.SUBTEXT),
    CARD_TITLE: toCSS(TOKEN_DEFS.CARD_TITLE),
    BADGE: toCSS(TOKEN_DEFS.BADGE),
    STAT: toCSS(TOKEN_DEFS.STAT),
    STAT_LARGE: toCSS(TOKEN_DEFS.STAT_LARGE),
    WIDGET_LABEL: toCSS(TOKEN_DEFS.WIDGET_LABEL),
    BANNER_HEADING: toCSS(TOKEN_DEFS.BANNER_HEADING),
    BANNER_BODY: toCSS(TOKEN_DEFS.BANNER_BODY),
    ERROR: toCSS(TOKEN_DEFS.ERROR),
    FOOTNOTE: toCSS(TOKEN_DEFS.FOOTNOTE),
    MODAL_TITLE: toCSS(TOKEN_DEFS.MODAL_TITLE),
    MODAL_BODY: toCSS(TOKEN_DEFS.MODAL_BODY),
    BUTTON_TEXT: toCSS(TOKEN_DEFS.BUTTON_TEXT),

    // React-compatible objects
    R: TOKEN_DEFS,
  },
  COLORS: {
    RED: COLORS.red,
    GREEN: COLORS.green,
    MUTED: COLORS.muted,
    TEXT: COLORS.text,
    ACCENT: COLORS.accent,
    ON_ACCENT: COLORS.onAccent,
    BORDER: COLORS.border,
    SURFACE: COLORS.surface,
  },
};
